config/routes.rb
Rails.application.routes.draw do
  resources :batches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/batches/:id/print_labels' => 'batches#print_labels', via: :get, :as => :print_labels

  match 'test_label.:format' => 'batches#test_label', via: :get

  root :to => "batches#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch.rb
require 'csv'

class Batch < ApplicationRecord
  has_attached_file :csv_original
  has_attached_file :csv_processed

  do_not_validate_attachment_file_type :csv_original
  do_not_validate_attachment_file_type :csv_processed

  after_create :process_original_csv!

  def process_original_csv!

    csv_string = Paperclip.io_adapters.for(csv_original).read
    parsed_csv = CSV.parse(csv_string)

    # Remove header row, assign indexes
    header_row = parsed_csv.shift
    order_number_column_index = header_row.index("Order - Number")
    item_location_column_index = header_row.index("Item - Location") + 1
    shelf_column_index = order_number_column_index + 1

    # Add Shelf to header
    header_row.insert(shelf_column_index, "Shelf")

    # Sort by order number
    parsed_csv.sort!{ |a,b| b[order_number_column_index].to_i <=> a[order_number_column_index].to_i }

    # Start with first order ID
    current_order_id = parsed_csv[0][order_number_column_index]
    current_shelf_number = 1

    parsed_csv.map! do |line_item|

      if line_item[order_number_column_index] != current_order_id
        current_shelf_number += 1
        current_order_id = line_item[order_number_column_index]
      end

      line_item.insert(shelf_column_index, current_shelf_number)
    end

    parsed_csv.sort!{ |a,b| a[item_location_column_index].to_s <=> b[item_location_column_index].to_s }

    generated_csv = CSV.generate do |csv|
      csv << header_row

      # Insert rows without blank item locations
      parsed_csv.each { |r| csv << r unless r[item_location_column_index].to_s == "" }

      # Insert rows with blank item locations
      parsed_csv.each { |r| csv << r if r[item_location_column_index].to_s == ""  }    
    end

    self.csv_processed = StringIO.new(generated_csv)
    self.csv_processed_file_name = csv_original.original_filename.gsub(/\.csv/, '_processed.csv')
    
    save
  end

  def print_labels!
    
    line_items = line_items_for_printing

    auth = PrintNode::Auth.new("dc4d7e31c7fac62d29cf9c833a7b8f793cc833fb")
    client = PrintNode::Client.new(auth)

    my_printer_id = 196762 #client.printers[0].id

    options = {} #For options argument in create_printjob
    options['options'] = {'bin' => '1'}
    options['expireAfter'] = 120000
    options['qty'] = 1

    line_items.each do |line_item|

      html = ApplicationController.render(:partial => "batches/label", :locals => line_item)

      kit = PDFKit.new(html, 
        :page_height => "50.8mm", 
        :page_width => "101.6mm", 
        :margin_top => "0mm",
        :margin_right => "0mm",
        :margin_bottom => "0mm",
        :margin_left => "0mm"
      ) # kit.to_pdf

      my_printjob_info = PrintNode::PrintJob.new(my_printer_id, 'Krewella Test Label', 'pdf_base64', Base64.encode64(kit.to_pdf), 'PicknPack')

      #Now we can create our printjob.
      my_printjob = client.create_printjob(my_printjob_info,options)

      #We can now see our our the information of our printjob using the id we got from create_printjob.
      my_printjob_info = client.printjobs(my_printjob)
    end

    update_attribute :label_printed, true
  end

  def line_items_for_printing
    csv_string = Paperclip.io_adapters.for(csv_processed).read
    parsed_csv = CSV.parse(csv_string)

    header_row = parsed_csv.shift
    
    index_item_name = header_row.index("Item - Name")
    index_item_quantity = header_row.index("Item - Qty")
    index_item_sku = header_row.index("Item - SKU")
    index_shelf = header_row.index("Shelf")
    index_order_number = header_row.index("Order - Number")
    index_item_location = header_row.index("Item - Location")
    index_item_image = header_row.index("Item - Image URL")

    parsed_csv.map do |line|
      {
        item_name: line[index_item_name],
        item_quantity: line[index_item_quantity],
        item_sku: line[index_item_sku],
        shelf: line[index_shelf],
        order_number: line[index_order_number],
        item_location: line[index_item_location],
        item_image: line[index_item_image]
      }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  
  def index
    @batches = Batch.all.order(:created_at => :desc)
  end

  def create
    if @batch = Batch.create!(batch_params)
      redirect_to :back
    else
      render text: @batch.errors.inspect
    end
  end

  def print_labels
    @batch = Batch.find(params[:id])
    @batch.print_labels!

    respond_to do |format|
      format.html { redirect_back fallback_location: '/' }
      format.js  { render :nothing => true, :status => 200 }
    end    
  end

  def test_label
    line_item = Batch.first.line_items_for_printing.first
    html = ApplicationController.render(:partial => "batches/label", :locals => line_item)
    kit = PDFKit.new(html, 
      :page_height => "50.8mm", 
      :page_width => "101.6mm", 
      :margin_top => "0mm",
      :margin_right => "0mm",
      :margin_bottom => "0mm",
      :margin_left => "0mm"
    )

    respond_to do |format|
      format.pdf do
        send_data kit.to_pdf, :filename => "label.pdf"
      end
    end
  end

  private

    def batch_params
      params.require(:batch).permit(:csv_original)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg_icon_tag(icon)
    File.read(File.join(Rails.root, "app/assets/images/#{icon}.svg")).html_safe
  end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_label.html.erb
<%
  require 'base64'
  require 'chunky_png'
  require 'barby'
  require 'barby/barcode/code_128'
  require 'barby/outputter/png_outputter'

  order_number_barcode = Barby::Code128B.new(order_number)
  order_number_barcode = Barby::PngOutputter.new(order_number_barcode).to_png(:height => 30, :xdim => 2)

  encoded_number = Base64.encode64(order_number_barcode)
%>

<html>
  <head>
    <style>
      div {
        margin-bottom: 5px;
        font-size: 16px;
        font-family: sans-serif;
      }

      table {
        width: 100%;
      }

      td {}

      td:first-child div {
        margin: 0;
      }

      td:first-child {
        text-align: center;
      }

      td:last-child {
        padding-left: 10px;
      }
    </style>
  </head>
  <body>
    <table>
      <tr>
        <td width="30%">
          <img src="<%= item_image %>" width="100%" />
          <div><%= item_sku %></div>
        </td>
        <td>
          <div><%= item_name %></div>
          <div><label>Location:</label> <%= item_location %></div>
          <div><label>Pick QTY:</label> <%= item_quantity %></div>
          <div><label>Shelf:</label> <%= shelf %></div>
          <div><label>Order #:</label> <%= order_number %></div>

          <img src="data:image/png;base64,<%= encoded_number %>"/>
        </td>
      </tr>
    </table>
  </body>
</html>

app/views/batches/index.html.erb
<div style="visibility:hidden; opacity:0" id="dropzone">
    <div id="textnode">Drop to process!</div>
</div>

<!-- <audio>
  <source src="/ding.wav" type="audio/wav">
</audio>
 -->
<%= form_for Batch.new do |f| %>
  <%= f.file_field :csv_original %>
  <%= f.submit "Upload File" %>
<% end %>

<script>
  $(function(){
    // $("audio").get(0).play();
  })
</script>

<h1>Pick-n-Pack</h1>

<div class="batches">
  <table>
    <tr>
      <th>Date</th>
      <th>Filename</th>
      <th>Print</th>
    </tr>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.created_at.strftime("%m/%d") %></td>

        <td class="filename">
          <%= link_to svg_icon_tag(:history), batch.csv_original.url, :title => "Download original CSV" %>
          <%= link_to batch.csv_original.original_filename, batch.csv_processed.url %>
        </td>

        <td class="print-labels <%= 'labels-printed' if batch.label_printed? %>">
          <%= link_to (batch.label_printed? ? '#' : print_labels_path(batch.id)), :rel => "nofollow" do %>
            <%= svg_icon_tag :print %>
            
            <% if batch.label_printed? %>
              <span class="check"><%= svg_icon_tag :circle_checkmark %></span>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicknPack</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>